/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fr.nadia.javascript;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Administrateur
 */
public class Taxe extends javax.swing.JFrame {

    /**
     * Creates new form taxe
     */
    public Taxe() {
        initComponents();
        populateCombo();
    }
    
    private void populateCombo(){
        //ajout on commence par reccuperer le model existant de la liste
        DefaultComboBoxModel model = (DefaultComboBoxModel)fruitsComboBox.getModel();
        model.addElement("citron");
        model.addElement("kiwi");
        
        //remplacement des données d une liste
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        model2.addElement("navet");
        model2.addElement("pomme de terre");
        model2.addElement("topinambour");
        
        //affecter le nouveau model à la combo
        fruitsComboBox.setModel(model2);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTva = new javax.swing.ButtonGroup();
        label = new javax.swing.JLabel();
        montantHTTextField = new javax.swing.JTextField();
        calcbutton = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        montantTTCTextField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        tva20RadioButton = new javax.swing.JRadioButton();
        tva15RadioButton = new javax.swing.JRadioButton();
        tva7RadioButton = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        fruitsComboBox = new javax.swing.JComboBox();
        ComboResultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setText("montant hors taxe");

        montantHTTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                montantHTTextFieldFocusGained(evt);
            }
        });

        calcbutton.setBackground(new java.awt.Color(102, 255, 255));
        calcbutton.setText("Calculer");
        calcbutton.setActionCommand("Vadider");
        calcbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcbuttonActionPerformed(evt);
            }
        });

        label3.setText("montant TTC");

        montantTTCTextField.setEnabled(false);

        jTextField2.setBackground(new java.awt.Color(255, 51, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("TAXE");

        buttonGroupTva.add(tva20RadioButton);
        tva20RadioButton.setText("20%");

        buttonGroupTva.add(tva15RadioButton);
        tva15RadioButton.setText("15.50%");

        buttonGroupTva.add(tva7RadioButton);
        tva7RadioButton.setText("7%");

        buttonGroupTva.add(jCheckBox1);
        jCheckBox1.setText("jCheckBox1");

        fruitsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pomme ", "Orange", "Bavane" }));
        fruitsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fruitsComboBoxItemStateChanged(evt);
            }
        });

        ComboResultLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(calcbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montantHTTextField)
                            .addComponent(montantTTCTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tva20RadioButton)
                        .addGap(42, 42, 42)
                        .addComponent(tva15RadioButton)
                        .addGap(46, 46, 46)
                        .addComponent(tva7RadioButton)))
                .addGap(29, 29, 29)
                .addComponent(jCheckBox1)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addComponent(fruitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboResultLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montantHTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tva15RadioButton)
                    .addComponent(tva20RadioButton)
                    .addComponent(tva7RadioButton)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(montantTTCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(fruitsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboResultLabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcbuttonActionPerformed
       System.out.println("je suis cliqué");
       //RECCUPERER LE MONTANT HT saisi
       Double montantHT = Double.valueOf(montantHTTextField.getText());
       Double result;
       Double taux;
       if(tva20RadioButton.isSelected()){
           taux = 1.2;
       }else if(tva15RadioButton.isSelected()){
           taux = 1.155;
       }else{
           taux = 1.07;
           tva7RadioButton.setSelected(true);
       }
      result = taux * montantHT;
      montantTTCTextField.setText(result.toString());
     
      //redonner le focus au champ de saisie du montant HT
      montantHTTextField.requestFocus();
      
    }//GEN-LAST:event_calcbuttonActionPerformed

    private void montantHTTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_montantHTTextFieldFocusGained
       montantHTTextField.selectAll();
    }//GEN-LAST:event_montantHTTextFieldFocusGained

    private void fruitsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fruitsComboBoxItemStateChanged
       ComboResultLabel.setText(
       fruitsComboBox.getSelectedIndex() + " "
               +fruitsComboBox.getSelectedIndex()
         
       );
       
    }//GEN-LAST:event_fruitsComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taxe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComboResultLabel;
    private javax.swing.ButtonGroup buttonGroupTva;
    private javax.swing.JButton calcbutton;
    private javax.swing.JComboBox fruitsComboBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField montantHTTextField;
    private javax.swing.JTextField montantTTCTextField;
    private javax.swing.JRadioButton tva15RadioButton;
    private javax.swing.JRadioButton tva20RadioButton;
    private javax.swing.JRadioButton tva7RadioButton;
    // End of variables declaration//GEN-END:variables
}
